/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pop_gestordedescargas;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Rectangle;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ProgressBar;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIDefaults;
import javax.swing.UIManager;
import sun.swing.UIAction;

/**
 *
 * @author strike
 */
public class GestorDeDescargas extends javax.swing.JFrame implements Runnable {

    private ProcessBuilder test;
    private Thread hilo;
    private Process p = null;
    private Boolean funcionando = false;
    private int porcentaje;
    private AnimacionBotonDescarga animacionBoton;

    /**
     * Creates new form GestorDeDescargas
     */
    public GestorDeDescargas() {
        initComponents();

        //Ponemos el porcentaje numerico en el progress bar
        barraProgreso.setStringPainted(true);

        //Cambiamos colores de la consola
        consola.setBackground(Color.BLACK);
        consola.setForeground(Color.GREEN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        panelGestor = new javax.swing.JPanel();
        barraProgreso = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextArea();
        panel = new javax.swing.JLabel();
        bDescargar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nVelocidadMax = new javax.swing.JComboBox<>();
        nConexiones = new javax.swing.JComboBox<>();
        buscarDestino = new javax.swing.JButton();
        tfDestino = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfOrigen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barraProgreso.setBackground(new java.awt.Color(51, 255, 51));

        consola.setEditable(false);
        consola.setColumns(20);
        consola.setRows(5);
        consola.setFocusable(false);
        jScrollPane1.setViewportView(consola);

        panel.setFont(new java.awt.Font("Ubuntu Medium", 0, 36)); // NOI18N
        panel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.setText("Gestor de Descargas ");

        bDescargar.setText("Descargar");
        bDescargar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bDescargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDescargarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel4.setText("Velocidad Máxima Kb/s");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel3.setText("Nº de Conexiones");

        nVelocidadMax.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "512", "1024", "2048", "4096", "8192" }));

        nConexiones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "4", "6", "8" }));

        buscarDestino.setText("+");
        buscarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDestinoActionPerformed(evt);
            }
        });

        tfDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDestinoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel2.setText("Destino Descarga");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLabel1.setText("Origen Descarga");

        tfOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOrigenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGestorLayout = new javax.swing.GroupLayout(panelGestor);
        panelGestor.setLayout(panelGestorLayout);
        panelGestorLayout.setHorizontalGroup(
            panelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestorLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelGestorLayout.createSequentialGroup()
                        .addGroup(panelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(57, 57, 57)
                        .addGroup(panelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nVelocidadMax, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nConexiones, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(panelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGestorLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(tfOrigen)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestorLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(bDescargar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGestorLayout.setVerticalGroup(
            panelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nConexiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nVelocidadMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(panelGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buscarDestino)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bDescargar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        getContentPane().add(panelGestor, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOrigenActionPerformed

    private void tfDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDestinoActionPerformed

    private void buscarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDestinoActionPerformed

        //Generamos un JFileChooser para recoger la ruta
        JFileChooser chooser = new JFileChooser();

        //Introducimos en directorio que por defecto mostrará el JFileChooser
        chooser.setCurrentDirectory(new java.io.File("/home"));

        String choosertitle = null;
        chooser.setDialogTitle(choosertitle);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        chooser.setAcceptAllFileFilterUsed(false);
        //
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            tfDestino.setText(chooser.getSelectedFile().toString());
        } else {
            consola.setText("No se ha seleccionado ningún directorio");
        }
    }//GEN-LAST:event_buscarDestinoActionPerformed

    private void bDescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDescargarActionPerformed

        //Creamos el comando de axel
        Runtime r = Runtime.getRuntime();
        String comando = "axel" + " -n " + nConexiones.getSelectedItem().toString() + " -s " + Integer.parseInt(nVelocidadMax.getSelectedItem().toString()) * 1024 + " --output=" + tfDestino.getText() + " " + tfOrigen.getText();

        //Empezamos la animacion de la descarga
        animacionBoton = new AnimacionBotonDescarga(bDescargar);

        //Preparamos el candado del hilo para parar su ejecución junto con la del axel
        funcionando = true;
        hilo = new Thread(this);
        hilo.start();

        //Lanzamos axel
        try {
            p = r.exec(comando); // Ejecutamos comando
        } catch (IOException ex) {

        }

        //Cambiamos la variable que hará terminar el while que contiene el hilo
        funcionando = false;
    }//GEN-LAST:event_bDescargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorDeDescargas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorDeDescargas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorDeDescargas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorDeDescargas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorDeDescargas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDescargar;
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JButton buscarDestino;
    private javax.swing.JTextArea consola;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> nConexiones;
    private javax.swing.JComboBox<String> nVelocidadMax;
    private javax.swing.JLabel panel;
    private javax.swing.JPanel panelGestor;
    private javax.swing.JTextField tfDestino;
    private javax.swing.JTextField tfOrigen;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {

        //variable con la que distinguiremos si se han realizado errores durante la ejecución
        String lineaError = null;

        //El hilo se ejecuta hata que la variable boleana "funcionando" pase a false
        //Dicho momento sucede cuando termina la ejecución de axel
        while (funcionando) {
            String linea;
            try {

                //Le damos un retraso a la ejecución del hilo
                Thread.sleep(200);

                //Leemos la salida de la consola para ir mostrandola en el TextArea
                BufferedReader br = new BufferedReader(new InputStreamReader(p.getInputStream()));
                while ((linea = br.readLine()) != null) // lee una linea
                {
                    //Leyendo la informacion de la consola sacamos el porcentaje de progreso y lo 
                    // actualizamos en el progress bar
                    porcentaje = sacarNumero(linea);
                    if (porcentaje > 0) {
                        barraProgreso.setValue(porcentaje);

                        //Cambiamos el color de fondo segun el porcentaje completado
                        panelGestor.setBackground(new Color(102,102, 255,porcentaje/2));                  
                    }

                    //Generamos la animación en el boton de descarga
                    animacionDescarga();

                    //Introducimos el texto de la consola en el JTextArea
                    consola.setText(consola.getText() + "\n" + linea);
                    consola.setCaretPosition(consola.getDocument().getLength());
                }
                br.close();

            } catch (InterruptedException e) {
                continue;
            } catch (IOException ex) {
                Logger.getLogger(GestorDeDescargas.class.getName()).log(Level.SEVERE, null, ex);
            }

            //Comprobamos si hay errores durante la ejecución, si es el caso mostraremos el mensaje
            try {
                BufferedReader br = new BufferedReader(new InputStreamReader(p.getErrorStream()));
                while ((linea = br.readLine()) != null) { // lee una linea
                    lineaError = linea;
                    JOptionPane.showMessageDialog(new Frame(), "La descarga se detuvo inesperadamente");
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        //finalizamos la animacion del boton de descarga
        animacionBoton.terminarAnimacion();

        //Pasamos el valor de la barra de progreso a 100
        barraProgreso.setValue(100);
        
        //Reiniciar color de fondo
         panelGestor.setBackground(new Color(214,217,223));   

        //Comprobamos si ha habido errores 
        if (lineaError == null) {
            JOptionPane.showMessageDialog(new Frame(), "La descarga se ha realizado con éxito");
        }

        
        //Pasamos el valor de la barra de progreso a 0
        barraProgreso.setValue(0);
    }

    public int sacarNumero(String linea) {
        int num = 0;
        try {
            num = Integer.parseInt(linea.substring(2, linea.indexOf("%")).trim());
        } catch (IndexOutOfBoundsException e) {
        } catch (NumberFormatException e) {
        }
        return num;
    }

    public void animacionDescarga() {

    }

}
